org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
mod_version=1.4.0

minecraft_version = 1.20.1
parchment_version = 2023.09.03
ars_version=4.12.6.253
forge_version=47.3.33

jei_version=15.20.0.106
gecko_version=4.7.1.2
curio_version=5.12.1+1.20.1
starbunclemania_version=1.2.3.0

create_version = 6.0.4-79
flywheel_version = 1.0.2
registrate_version = MC1.20-1.3.3
ponder_version = 1.0.52
spongepowered_mixin = 0.8.5
mixin_version = 0.4.1